const fs = require('fs')

class Cart {
    constructor({ id, products, ...props }) {
        this.id = id
        this.products = products
    }

    getData = () => {
        return ({
            id: this.id,
            products: this.products,
        })
    }
}

module.exports = class CartManager {
    constructor(path) {
        //Setea el path
        this.path = path

        //Obtiene los productos
        let carts = fs.readFileSync(this.path)
        carts = JSON.parse(carts)

        //Fija el ID como el mayor número de todos los ID +1
        this.id = +carts.reduce((acc, val) => {
            return acc > val.id ? acc : val.id;
        }, 0) + 1
    }

    //Return all carts
    getCarts = () => {
        let carts = fs.readFileSync(this.path)
        return JSON.parse(carts)
    }

    getCartById = (id) => {
        const carts = this.getCarts()
        const cart = carts.filter((cart) => cart.id === id)

        //If the cart exists return the product
        return cart.toString() === "" ? "Not found" : cart[0].products
    }

    addCart = ({ products, ...props }) => {
        let carts = this.getCarts()

        //New cart instance
        const cart = new Cart({
            id: this.id, //use the autogenerated id 
            products: []
        })
        carts.push(cart.getData())

        //Save the file
        fs.writeFileSync(this.path, JSON.stringify(carts))

        //Add 1 to the id
        ++this.id
        return carts
    }

    addProductToCart = ({ cid, pid, ...props }) => {
        const carts = this.getCarts()
        const cartIndex = carts.findIndex((cart) => cart.id === Number(cid))

        if (cartIndex < 0) {
            console.log("Not found")
        } else {
            console.log(typeof (pid))
            const productIndex = carts[cartIndex].products.findIndex((product) => product.product === pid)
            console.log(carts[cartIndex].products)
            if (productIndex < 0) {
                carts[cartIndex].products.push({ product: pid, quantity: 1 })
            } else {
                carts[cartIndex].products[productIndex].quantity = carts[cartIndex].products[productIndex].quantity + 1

            }
        }
        //Save the file
        fs.writeFileSync(this.path, JSON.stringify(carts))
        return (carts)
    }


}
